### PR TITLE
Group URLs by anchor

### PR DESCRIPTION
**Pull request by okom3pom**
Hi,

I am newbie to matomo and I don't understand the translations, i need to open an account https://www.transifex.com/ ?

Related : https://github.com/DevDavido/performance-audit-plugin/issues/33

### CODE REVIEW

**Comment by DevDavido** [comment]
> I am newbie to matomo and I don't understand the translations, i need to open an account https://www.transifex.com/ ?

There's no need to open an account with that service, simply edit the JSON file `lang/en.json`.

**Comment by DevDavido** [comment]
Since it's WIP I'm going to wait until you finish with your PR before merging.

**Comment by okom3pom** [comment]
Hi @DevDavido 

The WIP was for the translations, I come back from hollydays sorry for the response time.

I edit the title

**Comment by DevDavido** [comment]
OK thanks, I'll have a look on it when I have some time.

**Pull request merged**
